adverb_list = []
adverb_list.append(("あるいは",          "あるいは", [["lemma"]]))
adverb_list.append(("案外",              "案外", [["lemma", "pos"]]))
#adverb_list.append(("案の定",            "推量副詞", [["lemma", "pos"]]))
#adverb_list.append(("やはり",            "やはり", [["lemma", "pos"]]))
#adverb_list.append(("めずらしく",        "推量副詞", [["lemma", "pos"]]))
#adverb_list.append(("意外にも",          "推量副詞", [["lemma", "pos"], ["lemma"], ["lemma"]]))
#adverb_list.append(("かえって",          "推量副詞", [["lemma", "pos"]]))
adverb_list.append(("恐らく",            "恐らく", [["lemma"]]))
adverb_list.append(("おおかた",          "おおかた", [["lemma"]]))
adverb_list.append(("必ずしも",          "必ずしも", [["lemma"], ["lemma", "pos"]]))
adverb_list.append(("必ず",              "必ず", [["lemma"]]))
adverb_list.append(("きっと",            "きっと", [["lemma"]]))
adverb_list.append(("ことによると",      "ことによると", [["lemma"], ["lemma"], ["lemma"], ["lemma"]]))
adverb_list.append(("ことによれば",      "ことによると", [["lemma"], ["lemma"], ["lemma"], ["lemma", "cForm"]]))
#adverb_list.append(("によれば",          "によれば", [["lemma"], ["lemma"], ["lemma"]]))
#adverb_list.append(("に従えば",          "", [["lemma"], ["lemma"], ["lemma"]]))
adverb_list.append(("さぞ",              "さぞ", [["lemma"]]))
#adverb_list.append(("さぞかし",          "", [["lemma"]]))
adverb_list.append(("大概",              "大概", [["lemma", "pos"]]))
adverb_list.append(("大抵",              "大抵", [["lemma", "pos"]]))
adverb_list.append(("多分",              "多分", [["lemma"]])) # should really be able to specify more than one feature per morpheme
adverb_list.append(("どうも",            "どうも", [["lemma", "pos1"], ["lemma", "pos1"]]))
adverb_list.append(("どうやら",          "どうやら", [["lemma", "pos1"], ["lemma", "pos1"]]))
#adverb_list.append(("どうしても行かない","", [["lemma"], ["lemma"], ["lemma"], ["lemma"], ["pos1"], ["lemma"]]))
#adverb_list.append(("どうしても",        "", [["lemma"], ["lemma"], ["lemma"], ["lemma"]]))
#adverb_list.append(("何とか",            "推量副詞", [["lemma"], ["lemma"], ["lemma"]]))
#adverb_list.append(("ぜひ",              "推量副詞", [["lemma", "pos1"]]))
#adverb_list.append(("なるべく",          "推量副詞", [["lemma", "pos1"]]))
adverb_list.append(("もしかしたら",      "もしかして／たら／すると", [["lemma"], ["lemma"], ["lemma"], ["lemma", "cForm"]]))
adverb_list.append(("もしかして",        "もしかして／たら／すると", [["lemma"], ["lemma"], ["lemma"], ["lemma", "cForm"]]))
adverb_list.append(("もしかすると",      "もしかして／たら／すると", [["lemma"], ["lemma"], ["lemma"], ["lemma", "cForm"]]))
adverb_list.append(("ひょっとしたら",    "ひょっとして／たら／すると", [["lemma"], ["lemma"], ["lemma", "cForm"]]))
adverb_list.append(("ひょっとすれば",    "ひょっとして／たら／すると", [["lemma"], ["lemma"], ["lemma", "cForm"]]))
adverb_list.append(("ひょっとすると",    "ひょっとして／たら／すると", [["lemma"], ["lemma"], ["lemma", "cForm"]]))
adverb_list.append(("よほど",            "よほど", [["lemma"]]))
adverb_list.append(("絶対",              "絶対（に）", [["lemma"]]))
adverb_list.append(("絶対に",            "絶対（に）", [["lemma"], ["lemma"]]))
#adverb_list.append(("さあ",              "推量副詞", [["lemma", "pos1"]]))
#adverb_list.append(("まあ",              "推量副詞", [["lemma", "pos1"]]))
#adverb_list.append(("なんやら",          "推量副詞", [["lemma", "pos1"], ["lemma", "pos1"]]))
#adverb_list.append(("はたして",          "推量副詞", [["lemma", "pos1"]]))
#adverb_list.append(("いったい",          "推量副詞", [["lemma", "pos1"]]))
#adverb_list.append(("もし",              "推量副詞", [["lemma"]]))
#adverb_list.append(("万一",              "推量副詞", [["lemma"]]))
#adverb_list.append(("仮に",              "推量副詞", [["lemma"], ["lemma"]]))
#adverb_list.append(("たとえ",            "推量副詞", [["lemma", "pos1"]]))
#adverb_list.append(("どうぞ",            "推量副詞", [["lemma", "pos1"]]))
#adverb_list.append(("どうか",            "推量副詞", [["lemma", "pos1"], ["pos1", "lemma"]]))
#adverb_list.append(("なにぶん",          "推量副詞", [["lemma", "pos1", "pos3"]]))
#adverb_list.append(("なにとぞ",          "推量副詞", [["lemma", "pos1"]]))
#adverb_list = []
##adverb_list.append(("あるいは",       "(Epistemic)あるいは", [["lemma"]]))
#adverb_list.append(("案外",              "予想予期", [["lemma", "pos"]]))
#adverb_list.append(("案の定",            "予想予期", [["lemma", "pos"]]))
#adverb_list.append(("やはり",            "予想予期", [["lemma", "pos"]]))
#adverb_list.append(("めずらしく",        "予想予期", [["lemma", "pos"]]))
#adverb_list.append(("意外にも",          "予想予期", [["lemma", "pos"], ["lemma"], ["lemma"]]))
#adverb_list.append(("かえって",          "予想予期", [["lemma", "pos"]]))
#adverb_list.append(("恐らく",            "Epistemic Suppositional", [["lemma"]]))
#adverb_list.append(("おおかた",          "Epistemic Suppositional", [["lemma"]]))
#adverb_list.append(("必ずしも",          "Epistemic Possibility", [["lemma"], ["lemma", "pos"]]))
#adverb_list.append(("必ず",              "Epistemic Necessity", [["lemma"]]))
#adverb_list.append(("きっと",            "Epistemic Necessity", [["lemma"]]))
#adverb_list.append(("ことによると",      "Epistemic Possibility", [["lemma"], ["lemma"], ["lemma"], ["lemma"]]))
#adverb_list.append(("によれば",          "Evidential", [["lemma"], ["lemma"], ["lemma"]]))
#adverb_list.append(("に従えば",          "Evidential", [["lemma"], ["lemma"], ["lemma"]]))
#adverb_list.append(("さぞ",              "Epistemic Suppositional", [["lemma"]]))
#adverb_list.append(("さぞかし",          "Epistemic Suppositional", [["lemma"]]))
#adverb_list.append(("大概",              "Epistemic Suppositional", [["lemma", "pos"]]))
#adverb_list.append(("大抵",              "Epistemic Suppositional", [["lemma", "pos"]]))
#adverb_list.append(("多分",              "Epistemic Suppositional", [["lemma"]])) # should really be able to specify more than one feature per morpheme
#adverb_list.append(("どうも",            "Evidential Conjecture", [["lemma", "pos1"], ["lemma", "pos1"]]))
#adverb_list.append(("どうやら",          "Evidential Conjecture", [["lemma", "pos1"], ["lemma", "pos1"]]))
#adverb_list.append(("どうしても行かない","Boulomaic", [["lemma"], ["lemma"], ["lemma"], ["lemma"], ["pos1"], ["lemma"]]))
#adverb_list.append(("どうしても",        "Deontic", [["lemma"], ["lemma"], ["lemma"], ["lemma"]]))
#adverb_list.append(("何とか",            "Boulomaic", [["lemma"], ["lemma"], ["lemma"]]))
#adverb_list.append(("ぜひ",              "Boulomaic", [["lemma", "pos1"]]))
#adverb_list.append(("なるべく",          "Boulomaic", [["lemma", "pos1"]]))
#adverb_list.append(("もしかしたら",      "Epistemic Possibility", [["lemma"], ["lemma"], ["lemma"], ["lemma", "cForm"]]))
#adverb_list.append(("もしかして",        "Epistemic Possibility", [["lemma"], ["lemma"], ["lemma"], ["lemma", "cForm"]]))
#adverb_list.append(("もしかすると",      "Epistemic Possibility", [["lemma"], ["lemma"], ["lemma"], ["lemma", "cForm"]]))
#adverb_list.append(("ひょっとしたら",    "Epistemic Possibility", [["lemma"], ["lemma"], ["lemma", "cForm"]]))
#adverb_list.append(("ひょっとすれば",    "Epistemic Possibility", [["lemma"], ["lemma"], ["lemma", "cForm"]]))
#adverb_list.append(("ひょっとすると",    "Epistemic Possibility", [["lemma"], ["lemma"], ["lemma", "cForm"]]))
#adverb_list.append(("よほど",            "Evidential Conjecture", [["lemma"]]))
#adverb_list.append(("絶対",              "Epistemic Necessity", [["lemma"]]))
#adverb_list.append(("絶対に",            "Epistemic Necessity", [["lemma"], ["lemma"]]))
#adverb_list.append(("さあ",              "Inducement", [["lemma", "pos1"]]))
#adverb_list.append(("まあ",              "Inducement", [["lemma", "pos1"]]))
#adverb_list.append(("なんやら",          "Inducement", [["lemma", "pos1"], ["lemma", "pos1"]]))
#adverb_list.append(("はたして",          "Interrogative", [["lemma", "pos1"]]))
#adverb_list.append(("いったい",          "Interrogative", [["lemma", "pos1"]]))
#adverb_list.append(("もし",              "Conditional", [["lemma"]]))
#adverb_list.append(("万一",              "Conditional", [["lemma"]]))
#adverb_list.append(("仮に",              "Conditional", [["lemma"], ["lemma"]]))
#adverb_list.append(("たとえ",            "Conditional", [["lemma", "pos1"]]))
#adverb_list.append(("どうぞ",            "Request", [["lemma", "pos1"]]))
#adverb_list.append(("どうか",            "Request", [["lemma", "pos1"], ["pos1", "lemma"]]))
#adverb_list.append(("なにぶん",          "Request", [["lemma", "pos1", "pos3"]]))
#adverb_list.append(("なにとぞ",          "Request", [["lemma", "pos1"]]))
    #adverbs = set(lemma for (orth, lemma, pos) in adverb_list)
    #for adverb in adverbs:
    #    print (adverb)
